FROM apache/airflow:2.9.3-python3.11

USER airflow

WORKDIR /opt/airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY airflow/dags /opt/airflow/dags

COPY . /opt/airflow/project
